.TH CMT_VA_ARGS 3 "LIBCMT" "CMT_VA_ARGS" "Function Attributes"

.SH NAME
CMT_VA_ARGS \- Variable arguments support for older compilers

.SH SYNOPSIS
.B #define INCL__VA_ARGS
.br
.B #include <LIBCMT/LIBCMT.h>

.SH DESCRIPTION
This library provides support for variable argument functions on **pre-C89** compilers.     
It defines macros and typedefs to work with `va_args`-style arguments, as an alternative
to `...` in function definitions.

.SH MACROS AND TYPES
.TP
.B \`va_list\`, \`VA_LIST\`
Typedef for creating your argument list.
.TP
.B \`va_arg\`, \`VA_ARG\`
Macro to get a variable from your `va_list` in your function.
.TP
.B \`va_copy\`, \`VA_COPY\`
Macro to copy a `va_list` address.
.TP
.B \`va_start\`, \`VA_START\`
Macro to get the address pointer of your argument list.
.TP
.B \`va_end\`, \`VA_END\`
Macro to end a `va_list` pointer.

.SH USAGE
Example:

.nf
.c
test(); // PROTOTYPE

int main()
{
    test(42, 42.0, "Hello world");
    return (0);
}

extern int printf(); // PROTOTYPE

test(start)
    int start;
{
    va_list x;
    va_list y;
    va_start(x, start);
    va_copy(y, x);
    printf("%d\nx:%f\n", start, va_arg(x, double));
    va_end(x);
    printf("y:%f\n", va_arg(y, double));
    printf("y:%s\n", va_arg(y, char *));
    va_end(y);
}
.fi

.SH SEE ALSO
.B CMT_KNR_STYLE(3),
.B LIBCMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
