.TH CMT_COMMA_OPERATOR 3 "LIBCMT" "CMT_COMMA_OPERATOR" "Comma Operator Support Check"

.SH NAME
CMT_COMMA_OPERATOR \- Detect compiler support for the comma operator

.SH SYNOPSIS
.B #define INCL__COMMA_OPERATOR
.br
.B #include <LIBCMT/LIBCMT.h>

.SH FILES
LIBCMT/CHECK_FEATURE/COMMA_OPERATOR.h

.SH DESCRIPTION
This header defines a feature-test macro indicating whether the compiler supports the comma operator.

.SH MACROS
.TP
.B IS__COMMA_OPERATOR__SUPPORTED
Defined when the compiler accepts the comma operator in expressions and macro contexts.

.SH DETAILS
The comma operator enables sequential evaluation of expressions while producing the value of the final expression.

.SH EXAMPLE
.nf
int a = (b++, funct(), c = 42, b += c, 66);
.fi

.SH NOTES
Useful when writing portable macros that rely on sequential evaluation semantics.

.SH SEE ALSO
.B LIBCMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
