.TH STDCALL 3 "LIBCMT" "STDCALL" "Calling Conventions"

.SH NAME
STDCALL \- Optimises functions to follow OS ABI calling-convention rules

.SH SYNOPSIS
.B #define INCL__STDCALL
.br
.B #include <LIBCMT/LIBCMT.h>

.SH DESCRIPTION
Defines a calling convention where function arguments are passed right-to-left on the stack and the callee is responsible for cleaning the stack.  
Used primarily by Windows APIs and supported by various compilers for binary-interface compatibility.  
On 32-bit systems, symbol decoration may be applied by the compiler.

.TP
.B STDCALL
Calling-convention macro following OS ABI rules.

.SH USAGE
.nf
int STDCALL WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, ...);
.fi

.SH NOTES
- Callee performs stack cleanup.
- Required in both declarations and definitions:
.nf
extern STDCALL int WinMain(...);
.fi
- Common in Win32 API interface layers.

.SH SEE ALSO
.B LIBCMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
