.TH CMT_NORETURN 3 "CMT" "CMT_NORETURN" "Function Attributes"

.SH NAME
CMT_NORETURN \- Marks functions that do not return

.SH SYNOPSIS
.B #define INCL__NORETURN
.br
.B #include <CMT/CMT.H>

.SH FILES
CMT/KEYWORDS/NORETURN.H

.SH DESCRIPTION
Defines a macro to inform the compiler that the function will not return to the caller, allowing for optimizations.

.TP
.B NORETURN, noreturn
Indicates that the function will terminate the program or never return.

.SH USAGE
.nf
NORETURN void terminate_program(void) {
    exit(0);
}

noreturn void terminate_program(void) {
    exit(0);
}
.fi

.SH NOTES
- Use this macro on functions that call 'exit()', '_exit()', or similar termination routines.
- Helps the compiler optimize code flow and remove unreachable code after calls to such functions.

.SH SEE ALSO
.B CMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
