.TH CMT_RAX 3 "LIBCMT" "CMT_RAX" "Register Access Macros"

.SH NAME
CMT_RAX \- Read CPU register RAX/EAX/AX into a variable

.SH WARNING
This subsystem is a WIP.
It may fail on some compilers, architectures, or operating systems.
Use at your own risk.

.SH SYNOPSIS
.B #define INCL__RAX
.br
.B #include <LIBCMT/LIBCMT.h>

.SH FILES
LIBCMT/ASM/RAX.h

.SH DESCRIPTION
CMT_RAX provides macros that read the current value of the CPU Intel's primary accumulator register into a C variable.
It supports:
- x86_64: RAX
- x86_32: EAX

.SH MACROS
.TP
.B GET_RAX(var), get_rax(var)
Moves the value from the active accumulator register into the provided variable.
Operand size adapts automatically to architecture.

.SH NOTES
On 32-bit systems, EAX is used.

.SH EXAMPLES
Read 64-bit RAX:
.nf
uint64_t v;
GET_RAX(v);
.fi

Read 32-bit EAX:
.nf
unsigned int v32;
GET_RAX(v32);
.fi

.SH SEE ALSO
.B CMT_ARCHITECTURE(3),
.B LIBCMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
