.TH CMT_STRINGIFICATION 3 "CMT" "CMT_STRINGIFICATION" "Stringification Support Check"

.SH NAME
CMT_STRINGIFICATION \- Detect compiler support for the stringification operator

.SH SYNOPSIS
.B #define INCL__STRINGIFICATION
.br
.B #include <CMT/CMT.H>

.SH FILES
CMT/CHECK_FEATURE/STRINGIFICATION.H

.SH DESCRIPTION
This header defines a macro indicating whether the compiler supports the stringification operator (`#`).

.SH MACROS
.TP
.B IS__STRINGIFICATION__SUPPORTED
Defined when the compiler supports stringification concatenation via `#`.

.SH DETAILS
Stringification convert any pure input to macro to string in compiler time.

.SH EXAMPLE
.nf
#define X(A) #A

printf( X( i am testing something ) ); // Will return: "i am testing something" without a new line.
.fi

.SH SEE ALSO
.B CMT_TOKEN_PASTING(3),
.B CMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
