.TH CMT_X17 3 "LIBCMT" "CMT_X17" "Register Access Macros"

.SH NAME
CMT_X17 \- Read CPU register X17 into a variable

.SH WARNING
This subsystem is a WIP.
It may fail on some compilers, architectures, or operating systems.
Use at your own risk.

.SH SYNOPSIS
.B #define INCL__X17
.br
.B #include <LIBCMT/LIBCMT.h>

.SH FILES
LIBCMT/ASM/X17.h

.SH DESCRIPTION
CMT_X17 provides macros that read the current value of the CPU ARM64's X17 register into a C variable.
It supports:
- ARM_64: X17

.SH MACROS
.TP
.B GET_X17(var), get_x17(var)
Moves the value from the active accumulator register into the provided variable.
Operand size adapts automatically to architecture.

.SH NOTES
On 32-bit systems, EAX is used.

.SH EXAMPLES
Read 64-bit X17:
.nf
uint64_t v;
GET_X17(v);
.fi

.SH SEE ALSO
.B CMT_ARCHITECTURE(3),
.B LIBCMT(3)

.SH AUTHOR
Teoman Deniz <te.odenizgml@gmail.com>
